/***
 * This header is a stub, usually it's generated by cmake at when configuring the project.
 */

#pragma once

namespace Thunder
{
    namespace PluginHost {
        static constexpr uint8_t Major = 5;
        static constexpr uint8_t Minor = 0;
        static constexpr uint8_t Patch = 0;
    }
}
